# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{custom_fields}
  s.version = "0.0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Didier Lafforgue"]
  s.date = %q{2010-09-01}
  s.description = %q{Manage custom fields to a mongoid document or a collection. This module is one of the core features we implemented in our custom cms named Locomotive.}
  s.email = ["didier@nocoffee.fr"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "init.rb",
     "lib/custom_fields.rb",
     "lib/custom_fields/custom_fields_for.rb",
     "lib/custom_fields/extensions/mongoid/associations/embeds_many.rb",
     "lib/custom_fields/extensions/mongoid/associations/proxy.rb",
     "lib/custom_fields/extensions/mongoid/associations/references_many.rb",
     "lib/custom_fields/extensions/mongoid/hierarchy.rb",
     "lib/custom_fields/field.rb",
     "lib/custom_fields/proxy_class_enabler.rb",
     "lib/custom_fields/types/boolean.rb",
     "lib/custom_fields/types/category.rb",
     "lib/custom_fields/types/date.rb",
     "lib/custom_fields/types/default.rb",
     "lib/custom_fields/types/file.rb",
     "lib/custom_fields/types/string.rb",
     "lib/custom_fields/types/text.rb"
  ]
  s.homepage = %q{http://github.com/locomotivecms/custom_fields}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Custom fields plugin for Mongoid}
  s.test_files = [
    "spec/integration/custom_fields_for_spec.rb",
     "spec/integration/types/category_spec.rb",
     "spec/integration/types/file_spec.rb",
     "spec/models/person.rb",
     "spec/models/project.rb",
     "spec/models/task.rb",
     "spec/spec_helper.rb",
     "spec/support/carrierwave.rb",
     "spec/support/mongoid.rb",
     "spec/unit/custom_field_spec.rb",
     "spec/unit/custom_fields_for_spec.rb",
     "spec/unit/proxy_class_enabler_spec.rb",
     "spec/unit/types/boolean_spec.rb",
     "spec/unit/types/category_spec.rb",
     "spec/unit/types/date_spec.rb",
     "spec/unit/types/file_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

