require 'spec_helper'

describe 'Class generated by CustomFieldsFor' do

  before(:each) do
    (@blog = build_blog).save
  end

  it 'owns only one validator' do
    @blog.posts.build.class.validators.size.should == 2
  end

  it 'does not duplicate the list of validators if adding new fields' do
    3.times do |i|
      @blog.posts_custom_fields.build :label => "field #{i}", :type => 'string'
      @blog.save.should be_true
      @blog.send(:refresh_posts_metadata)
    end

    @blog = Blog.find(@blog._id) # hard reload
    @blog.posts.build.class.validators.size.should == 2

    @blog.klass_with_custom_fields(:posts).validators.size.should == 2
  end

  def build_blog
    Blog.new(:name => 'My personal blog').tap do |blog|
      blog.posts_custom_fields.build :label => 'Main Author',  :type => 'string', :required => true
      blog.posts_custom_fields.build :label => 'Location',     :type => 'string'
    end
  end
end
